language: objective-c
osx_image: xcode11.4

install:
  - brew update; brew outdated swiftlint || brew upgrade swiftlint

matrix:
  include:
    - env: JOB="XCODE" DEST="OS=12.0,name=iPhone X" SCHEME="RxBus-Demo-iOS"
    - env: JOB="XCODE" DEST="arch=x86_64" SCHEME="RxBus-Demo-macOS"
    - env: JOB="XCODE" DEST="OS=11.0,name=Apple TV 4K" SCHEME="RxBus-Demo-tvOS"

script:
  - set -o pipefail
  - cd Demo
  - xcodebuild test -workspace RxBus-Demo.xcworkspace -scheme "$SCHEME" -destination "$DEST" ENABLE_TESTABILITY=YES | xcpretty

notifications:
  email: false
  slack:
    rooms:
      secure: "oUiP/FdyKt8vdjfo1B7xfpnExeeiL1jF4dOvXSyMAUe040A8tQVels7txuCt6LgwKsrC796VOCyPWs7x2zt3FZ0fMYcxbdNoKvHI5twxLpy+kpejW2pzPV1Cni3K6yn8u44x/UXzQcKqyD4E+DyULJuLxO7OxZBQX9YgfoIkGO2uXo2M6IOCWlsVYq/HyvRiL6N4EASfaMCZCPMc3GV7jqu4WXOCGbrduxdDx6dbF2VmWqnbaGXSk8nfeeOJFv5jUauob9+nLaVeC/2i93MBSvHUHmSsS07kNEGt4UXhdSBxNhN7DjGxySCWkbH2YkVcuvq1xJbVx4XtTQPY2iI+AJ9NpEEpXujCTQTjl2kQLMmyRDJ3Nh8337aD0GkjYJI1VmKUhVG0ZnysLrdnoEWfblfS1u/OZQW7vSlqUvTZ6BwpdTzOSebr25u+EKGyGlBidQYMl5rcs0VXezYf2Vt7iUGRyBcgxdxK78B3mvT7HLRB1UHvNkTJ29aa5oX0KrbJch5FPG9EmLd+vgx2fWGQzw44tMyEHunS+YMzAFYFNl/Ai5piaxT6GySDL79fbvlxhbj0GXFu4BDKxbjlZsiM9Iu1/ZL041LlLFZ2qG/G0P1Prf1Z1whTKscOP6OrQE4j6cPZdKC8qdWeukQydTzxILEJx98IdUkxBdJTPmSKMME="
    on_success: change
