language: objective-c
osx_image: xcode10.2

install:
  - cd ./RxBus-Demo; pod update

matrix:
  include:
    - env: JOB="XCODE" DEST="OS=12.0,name=iPhone X" SCHEME="RxBus-Demo-iOS"
    - env: JOB="XCODE" DEST="arch=x86_64" SCHEME="RxBus-Demo-macOS"
    - env: JOB="XCODE" DEST="OS=11.0,name=Apple TV 4K" SCHEME="RxBus-Demo-tvOS"

script:
  - set -o pipefail
  - xcodebuild test -workspace RxBus-Demo.xcworkspace -scheme "$SCHEME" -destination "$DEST" -configuration Release ENABLE_TESTABILITY=YES | xcpretty

notifications:
  email: false
  slack:
    rooms:
      - "j5ENe3Az8JUQ1WxRHGXknNJt9YRJEoX2RpNX/qj/sAXMPMd8DJccoatAPUR/zwTKnNeWgnviokRkwIXu2G8YtPgTN+DjKw8yqG4X2z0PlNWmc/SZHUW/KQ7erhe2ShQ3vhP7+zlW/kGtyOqMVDU6kTFbImAWZsRGhRVC+3n0sXUCP3RxDKm/M9YZKrJzY/ezbKqX7PPqZ2xbO8PKPHJCuhT7UBrgqoBXiynNk48BOieRpIl6l+d3iH2/vuzkufeJjlbuMoxLmU1k2HOroK7cXIKKFPsAnqydK1bsPttrRkujSj3GuRtl8pmVlf6PUUIwd7pDTGLlmJbygqOEwv+w5M5nzGvZOOUFisKnfkfORFB6yoCsFVz3AeWERY0cBL4N9q8SJ+pTUy/2oX0pNtuMHlp/X6CWno51lqRRQ3o2IbvRUyB2fJeRoHlXJZIILQaIl9cQ9f9MaPvArzseUveUoJAyBjT4+hOB/jQqVp9voZlO6HxHf1Tyx7dVR7XtgnG+xdSpMv72mY5RXXm+Jm2BG3/xW+1NfYOaRr49HWMizmPfcx4j0jh/sMeggH7fJB2hQ8PSx+pnvmiWS6yGuZ1Lkoj5XyJ/yBk7RsoMk8/HGBJNIGXynW3R2OWbYgvj53ttM0YWnwKWow/cCxhVvmBwFVVmy9+XDcWZslbv1E9ZTks="
    on_success: change
